/**
 * Brain.js LSTM Advisor — Syngenta Field Force Intelligence
 *
 * Loads a pre-trained LSTM from src/data/brainModel.json (generated by
 * scripts/trainBrain.js). Provides:
 *   - getVelocityData()     → week-by-week actual + predicted for the chart
 *   - detectBrainAnomalies()→ bulk evaluation across all retailer+SKU combos
 *
 * No training at runtime — all inference is < 5ms per retailer+SKU.
 */

import path   from 'path';
import fs     from 'fs';
// Use browser bundle — no native `gl` / GPU dependency, pure JS, works on Render
// eslint-disable-next-line @typescript-eslint/no-var-requires
const brainBundle = require('brain.js/dist/browser.js') as {
  recurrent: { LSTMTimeStep: new (opts?: object) => any };
};
import POS       from '../models/POS';
import Inventory from '../models/Inventory';
import Retailer  from '../models/Retailer';

// ─── Types ────────────────────────────────────────────────────────────────────

interface BrainModelFile {
  model:         any;
  sku_max:       Record<string, number>;
  window:        number;
  products:      string[];
  hidden_layers: number[];
  network_type:  string;
  trained_at:    string;
  trained_on:    number;
  n_series:      number;
}

export interface WeekPoint {
  label:  string;   // "Mar W2"
  week:   string;   // "2026-03-09"
  actual: number;   // units sold
}

export interface VelocityData {
  sku:              string;
  weeks:            WeekPoint[];
  predicted:        number;        // LSTM predicted next-week units
  current_qty:      number;        // latest inventory snapshot
  days_to_stockout: number | null; // null = can't determine
  anomaly_type:     'brain_demand_spike' | 'brain_stockout_risk' | null;
  deviation:        number;        // actual / predicted ratio
}

// ─── Module state ─────────────────────────────────────────────────────────────

let net:       any | null = null;   // brain.js LSTM instance
let modelMeta: Omit<BrainModelFile, 'model'> | null = null;


// ─── Load / reload ────────────────────────────────────────────────────────────

export function loadBrainModel(): void {
  const candidates = [
    path.join(__dirname, '../data/brainModel.json'),
    path.join(process.cwd(), 'src/data/brainModel.json'),
  ];
  const modelPath = candidates.find(fs.existsSync) ?? candidates[0];

  if (!fs.existsSync(modelPath)) {
    console.warn('[Brain] brainModel.json not found — run: node scripts/trainBrain.js');
    return;
  }

  try {
    const file: BrainModelFile = JSON.parse(fs.readFileSync(modelPath, 'utf8'));
    const instance = new brainBundle.recurrent.LSTMTimeStep({ hiddenLayers: file.hidden_layers ?? [8] });
    instance.fromJSON(file.model);
    net       = instance;
    modelMeta = {
      sku_max:       file.sku_max,
      window:        file.window,
      products:      file.products,
      hidden_layers: file.hidden_layers ?? [8],
      network_type:  file.network_type ?? 'LSTMTimeStep',
      trained_at:    file.trained_at,
      trained_on:    file.trained_on,
      n_series:      file.n_series,
    };
    console.log(
      `[Brain] ✓ LSTM loaded — ${file.trained_on} sequences across ` +
      `${file.n_series} retailer+SKU series (${file.trained_at})`
    );
  } catch (err: any) {
    console.error('[Brain] Failed to load brainModel.json:', err.message);
  }
}

export function getBrainModelStatus() {
  return {
    trained:      net !== null,
    trained_on:   modelMeta?.trained_on    ?? 0,
    n_series:     modelMeta?.n_series      ?? 0,
    trained_at:   modelMeta?.trained_at    ?? null,
    window:       modelMeta?.window        ?? 0,
    hidden_layers: modelMeta?.hidden_layers ?? [],
    network_type: modelMeta?.network_type  ?? 'LSTMTimeStep',
    products:     modelMeta?.products      ?? [],
    inference:    'brain.js LSTMTimeStep (CPU, pure JS)',
  };
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

/** ISO date of the Monday that starts the week containing `date`. */
function weekKey(date: Date): string {
  const d   = new Date(date);
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  return new Date(d.getFullYear(), d.getMonth(), diff).toISOString().slice(0, 10);
}

/** "2026-03-09" → "Mar W2" */
function weekLabel(iso: string): string {
  const d    = new Date(iso);
  const mon  = d.toLocaleString('en-IN', { month: 'short' });
  const wNum = Math.ceil(d.getDate() / 7);
  return `${mon} W${wNum}`;
}

/**
 * Returns the latest transaction_date in the POS collection.
 * Cached for 10 minutes so we don't query on every velocity request.
 * Falls back to Date.now() if the collection is empty.
 * This anchors all lookback windows to the dataset's own timeline rather
 * than today's date — critical when synthetic data ends months ago.
 */
let _latestPosDate: Date | null = null;
let _latestPosFetchedAt = 0;

async function getLatestPosDate(): Promise<Date> {
  const now = Date.now();
  if (_latestPosDate && now - _latestPosFetchedAt < 10 * 60_000) return _latestPosDate;
  const doc = await POS.findOne().sort({ transaction_date: -1 }).select('transaction_date').lean();
  _latestPosDate     = doc?.transaction_date ? new Date(doc.transaction_date) : new Date();
  _latestPosFetchedAt = now;
  return _latestPosDate;
}

/** Run LSTM and return a numeric prediction (0–N units), or null on failure. */
function runNet(normalizedWindow: number[]): number | null {
  if (!net) return null;
  try {
    const raw = (net as any).run(normalizedWindow);
    return typeof raw === 'number' ? raw : null;
  } catch {
    return null;
  }
}

// ─── Velocity data for one retailer + SKU ─────────────────────────────────────

export async function getVelocityData(
  retailerId: string,
  skuName:    string,
): Promise<VelocityData | null> {
  if (!net || !modelMeta) return null;

  const WINDOW  = modelMeta.window;
  const maxVal  = modelMeta.sku_max[skuName] || 1;

  // Anchor to the dataset's latest date (not today) so synthetic historical
  // data is always within the lookback window regardless of deployment date
  const anchor = await getLatestPosDate();
  const since  = new Date(anchor.getTime() - (WINDOW + 5) * 7 * 86_400_000);
  const posDocs = await POS.find({
    retailer_id:      retailerId,
    sku_name:         skuName,
    transaction_date: { $gte: since },
  }).lean();

  if (!posDocs.length) return null;

  // Aggregate by week
  const weekMap = new Map<string, number>();
  for (const tx of posDocs) {
    const wk = weekKey(tx.transaction_date);
    weekMap.set(wk, (weekMap.get(wk) || 0) + tx.sku_qty);
  }

  const sorted = [...weekMap.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  if (sorted.length < WINDOW) return null;   // not enough history

  // Last WINDOW weeks are the model input
  const inputSlice    = sorted.slice(-WINDOW);
  const normInput     = inputSlice.map(([, u]) => Math.min(u / maxVal, 1));
  const rawPrediction = runNet(normInput);
  const predicted     = rawPrediction !== null
    ? Math.max(0, Math.round(rawPrediction * maxVal))
    : Math.round(inputSlice[inputSlice.length - 1][1]); // fallback: last actual

  // Current inventory
  const inv = await Inventory.findOne({ retailer_id: retailerId, sku_name: skuName })
    .sort({ week_end_date: -1 })
    .lean();
  const currentQty = inv?.sku_qty ?? 0;

  // Days to stockout (based on last 7-day run rate)
  const lastWeekActual  = sorted[sorted.length - 1]?.[1] ?? 0;
  const dailyRate       = lastWeekActual / 7;
  const daysToStockout  = dailyRate > 0 ? Math.floor(currentQty / dailyRate) : null;

  // Deviation: last-week actual vs predicted-for-last-week
  // We predict from the window BEFORE last week for a fairer comparison
  let deviation = 1;
  if (sorted.length >= WINDOW + 1) {
    const prevWindow   = sorted.slice(-(WINDOW + 1), -1);
    const prevNorm     = prevWindow.map(([, u]) => Math.min(u / maxVal, 1));
    const prevRaw      = runNet(prevNorm);
    const prevPredUnit = prevRaw !== null ? prevRaw * maxVal : prevWindow[prevWindow.length - 1][1];
    deviation = prevPredUnit > 0 ? lastWeekActual / prevPredUnit : 1;
  }
  deviation = Math.round(deviation * 100) / 100;

  // Classify anomaly
  let anomalyType: VelocityData['anomaly_type'] = null;
  if (deviation > 1.8) {
    anomalyType = 'brain_demand_spike';
  } else if (deviation < 0.4 || (daysToStockout !== null && daysToStockout < 7)) {
    anomalyType = 'brain_stockout_risk';
  }

  const weeks: WeekPoint[] = sorted.map(([wk, actual]) => ({
    label:  weekLabel(wk),
    week:   wk,
    actual,
  }));

  return {
    sku:              skuName,
    weeks,
    predicted,
    current_qty:      currentQty,
    days_to_stockout: daysToStockout,
    anomaly_type:     anomalyType,
    deviation,
  };
}

// ─── Top-selling SKU for a retailer ──────────────────────────────────────────

export async function getTopSkuForRetailer(retailerId: string): Promise<string | null> {
  if (!modelMeta) return null;
  const anchor = await getLatestPosDate();
  const since  = new Date(anchor.getTime() - 4 * 7 * 86_400_000);
  const agg    = await POS.aggregate([
    { $match: { retailer_id: retailerId, transaction_date: { $gte: since }, sku_name: { $in: modelMeta.products } } },
    { $group: { _id: '$sku_name', total: { $sum: '$sku_qty' } } },
    { $sort: { total: -1 } },
    { $limit: 1 },
  ]);
  return (agg[0] as any)?._id ?? null;
}

// ─── Bulk anomaly detection ───────────────────────────────────────────────────

export async function detectBrainAnomalies(): Promise<object[]> {
  if (!net || !modelMeta) return [];

  const anchor = await getLatestPosDate();
  const since  = new Date(anchor.getTime() - (modelMeta.window + 5) * 7 * 86_400_000);

  // All retailer+SKU combos with recent sales
  const combos = await POS.aggregate([
    {
      $match: {
        transaction_date: { $gte: since },
        sku_name:         { $in: modelMeta.products },
      },
    },
    {
      $group: {
        _id: { retailer_id: '$retailer_id', sku_name: '$sku_name' },
      },
    },
  ]);

  // Build territory map
  const retailerIds  = [...new Set(combos.map((c: any) => c._id.retailer_id))];
  const retailers    = await Retailer.find({ retailer_id: { $in: retailerIds } })
    .select('retailer_id territory_id')
    .lean();
  const territoryMap = new Map(retailers.map((r) => [r.retailer_id, r.territory_id]));

  const flags: object[] = [];

  for (const combo of combos) {
    const { retailer_id, sku_name } = (combo as any)._id;
    try {
      const vd = await getVelocityData(retailer_id, sku_name);
      if (!vd || !vd.anomaly_type) continue;

      const lastActual = vd.weeks[vd.weeks.length - 1]?.actual ?? 0;
      const isSpike    = vd.anomaly_type === 'brain_demand_spike';
      const severity   =
        (vd.days_to_stockout !== null && vd.days_to_stockout < 5) ? 'high' : 'medium';

      const description = isSpike
        ? `ML Demand Spike: ${sku_name} sold ${lastActual} units last week ` +
          `(${vd.deviation}× above LSTM forecast of ${vd.predicted})`
        : `ML Stockout Risk: ${sku_name} velocity dropped to ${lastActual} units/week` +
          (vd.days_to_stockout !== null
            ? ` — ${vd.days_to_stockout} days of stock remaining`
            : '');

      flags.push({
        retailer_id,
        territory_id: territoryMap.get(retailer_id) ?? 'unknown',
        anomaly_type: vd.anomaly_type,
        sku_name,
        severity,
        description,
      });
    } catch {
      // skip individual failures silently
    }
  }

  console.log(`[Brain] ${flags.length} ML anomalies detected across ${combos.length} retailer+SKU combos`);
  return flags;
}
